Ejemplos de NumPy

In [1]:
# Importamos la librería

import numpy as np

Vectores y Matrices

In [2]:
# Vectores
print("------------------------------------------")
print("VECTORES")
print("------------------------------------------")
V1 = np.array([0,1,2,3,4,5])
V2 = np.array([10,15,25,50,100])

print("El Vector 1 es {}".format(V1))

# Podemos llamar a elementos concretos del arreglo al igual que en las listas de python.
# Obs: Recuerden que python empieza a contar desde 0

elemento_1_V1 = V1[1]
primeros_3_elementos_V1 = V1[0:3]

print("El elemento 1 del vector 1 es {}".format(elemento_1_V1))
print("Los primeros 3 elementos del vector 1 son {}".format(primeros_3_elementos_V1))

# Incluso podemos hacer lo que se llama indexación booleana

Mayores_a_2_V1 = V1[V1>2]
print("Los elementos del V1 mayores a 2 son {}".format(Mayores_a_2_V1))

# Podemos ver la forma del vector

longitud_V1 = V1.shape[0]
print("La longitud del vector 1 es de {} elementos".format(longitud_V1))

------------------------------------------
VECTORES
------------------------------------------
El Vector 1 es [0 1 2 3 4 5]
El elemento 1 del vector 1 es 1
Los primeros 3 elementos del vector 1 son [0 1 2]
Los elementos del V1 mayores a 2 son [3 4 5]
La longitud del vector 1 es de 6 elementos


Matrices

In [3]:


print("------------------------------------------")
print("Matrices")
print("------------------------------------------")
# De forma análoga, podemos crear matrices. 
# En estos casos, dentro de np.array hay que pasar una lista de listas
M1 = np.array([[1,2,3],[4,5,6]])
M2 = np.array([[-1,2,-3],[4,-5,6]])

print("La segunda matriz es \n  {}".format(M2))

# Podemos hacer lo mismo que los vectores

print("El elemento 0,0 de la matriz 2 es {}".format(M2[0,0]))
print("La primera fila de la matriz 2 es {}".format(M2[0,:]))

print("La matriz 2 es de forma {};\nEs decir, tiene {} filas y {} columnas.".format(M2.shape,M2.shape[0],M2.shape[1]))

# También se puede encontrar la matriz traspuesta de M2

print("La matriz traspuesta de M2 es\n {}".format(M2.T)) # np.transpose también se puede usar



------------------------------------------
Matrices
------------------------------------------
La segunda matriz es 
  [[-1  2 -3]
 [ 4 -5  6]]
El elemento 0,0 de la matriz 2 es -1
La primera fila de la matriz 2 es [-1  2 -3]
La matriz 2 es de forma (2, 3);
Es decir, tiene 2 filas y 3 columnas.
La matriz traspuesta de M2 es
 [[-1  4]
 [ 2 -5]
 [-3  6]]


Operaciones básicas

In [4]:
# Sumas y restas
print("------------------------------------------")
print("Operaciones básicas")
print("------------------------------------------")

# Lo bueno es que las operaciones elemento a elemento vienen por default con los objetos de numpy
# Obs: Hay que sacarle un elemento a V1 porque tiene 6 elementos en vez de 5, que es lo que tiene V2

print("La suma de vectores es {}".format(V1[:5] + V2)) #np.add() se puede usar para lo mismo
print("La resta de matrices dá:\n {}".format(M1-M2)) #np.subtract() se puede usar para lo mismo



------------------------------------------
Operaciones básicas
------------------------------------------
La suma de vectores es [ 10  16  27  53 104]
La resta de matrices dá:
 [[ 2  0  6]
 [ 0 10  0]]


In [5]:
# Multiplicación y división elemento a elemento
print("La multiplicación de vectores elemento a elemento dá {}".format(V1[:5]*V2)) #  np.multiply
print("La división de matrices elemento a elemento dá\n {}".format(M1/M2)) # np.divide



La multiplicación de vectores elemento a elemento dá [  0  15  50 150 400]
La división de matrices elemento a elemento dá
 [[-1.  1. -1.]
 [ 1. -1.  1.]]


In [6]:
# Obs para vector vs matriz. Si el vector es del largo de las filas de las matrices
#  se multiplica fila x fila, elemento x elemento

print("Multiplicación elemento a elemento vector 1 x Matriz 2 dá \n {}".format(V1[:3]*M2))


Multiplicación elemento a elemento vector 1 x Matriz 2 dá 
 [[ 0  2 -6]
 [ 0 -5 12]]


Calculos sobre columnas o filas

In [7]:
print("------------------------------------------")
print("Filas o Columnas")
print("------------------------------------------")

print("La suma de las columnas de la matriz 2 dá {}".format(M2.sum(axis=0)))
print("El mínimo de las filas de la matriz 2 dá {}".format(M2.min(axis=1)))
print("La media de todos los valores de la matriz 2 da {}".format(M2.mean()))
print("La mediana de todos los valores de la matriz 2 da {}".format(np.median(M2)))
print("El desvío de todos los valores de la matriz 2 da {}".format(M2.std()))

------------------------------------------
Filas o Columnas
------------------------------------------
La suma de las columnas de la matriz 2 dá [ 3 -3  3]
El mínimo de las filas de la matriz 2 dá [-3 -5]
La media de todos los valores de la matriz 2 da 0.5
La mediana de todos los valores de la matriz 2 da 0.5
El desvío de todos los valores de la matriz 2 da 3.8622100754188224


Operaciones para cada elemento

In [8]:
print("------------------------------------------")
print("Operaciones para cada elemento")
print("------------------------------------------")

print("e elevado a cada elemento del vector 1 dá\n {}".format(np.exp(V1))) 
print("La raíz cuadrada de cada elemento del vector 1 dá\n {}".format(np.sqrt(V1)))
print("El seno de cada elemento del vector 1 dá\n {}".format(np.sin(V1)))
print("El coseno de cada elemento del vector 1 dá\n {}".format(np.cos(V1)))
print("El logaritmo natural cada elemento del vector 2 dá\n {}".format(np.log(V2)))


------------------------------------------
Operaciones para cada elemento
------------------------------------------
e elevado a cada elemento del vector 1 dá
 [  1.           2.71828183   7.3890561   20.08553692  54.59815003
 148.4131591 ]
La raíz cuadrada de cada elemento del vector 1 dá
 [0.         1.         1.41421356 1.73205081 2.         2.23606798]
El seno de cada elemento del vector 1 dá
 [ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
El coseno de cada elemento del vector 1 dá
 [ 1.          0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
El logaritmo natural cada elemento del vector 2 dá
 [2.30258509 2.7080502  3.21887582 3.91202301 4.60517019]


Multiplicación de matrices (dot product)

In [9]:
# Multiplicamos primero los vectores

print("La multiplicación de los vectores 1 y 2 dá {}".format(np.dot(V1[:5],V2))) 
# Obs: NumPy nos perdona que no hayamos traspuesto el vector. Pero con las matrices no es tán comprensivo

try:
    print("La multiplicación de las matrices 1 y 2 dá {}".format(np.dot(M1, M2)))
# Si esto tira error
except:
    print("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
    print("Hay que tener cuidado con las trasposiciónes")
    print("La multiplicación de las matrices 1 y 2 dá\n {}".format(np.dot(M1, M2.T)))

La multiplicación de los vectores 1 y 2 dá 615
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Hay que tener cuidado con las trasposiciónes
La multiplicación de las matrices 1 y 2 dá
 [[ -6  12]
 [-12  27]]


Comparar matrices y vectores

In [10]:
print("------------------------------------------")
print("Comparación")
print("------------------------------------------")

print("Comparando elemento a elemento las matrices 1 y 2 obtenemos que: \n{}".format(M1==M2))
print("Si comparamos la totalidad de los vectores 1 y 2 obtenemos que:\n{}".format(np.array_equal(V1,V2)))
print("Podemos ver si los elementos de la matriz 2 son mayores que 2 elemento a elemento:\n{}".format(M2>2))


------------------------------------------
Comparación
------------------------------------------
Comparando elemento a elemento las matrices 1 y 2 obtenemos que: 
[[False  True False]
 [ True False  True]]
Si comparamos la totalidad de los vectores 1 y 2 obtenemos que:
False
Podemos ver si los elementos de la matriz 2 son mayores que 2 elemento a elemento:
[[False False False]
 [ True False  True]]


Transformaciones a los arrays

In [11]:
print("------------------------------------------")
print("Transformaciones de arrays")
print("------------------------------------------")

print("Si aplanamos la matriz 2 obtenemos: \n{}".format(M2.ravel()))
print("Podemos cambiar de forma la matriz 1:\n{}".format(M1.reshape(3,2)))
print("Con el mismo reshape podemos 'verticalizar' los vectores. Por ejemplo el primero: \n{}".format(V1.reshape(-1,1))) # Obs, V1.T no funciona en estos casos




------------------------------------------
Transformaciones de arrays
------------------------------------------
Si aplanamos la matriz 2 obtenemos: 
[-1  2 -3  4 -5  6]
Podemos cambiar de forma la matriz 1:
[[1 2]
 [3 4]
 [5 6]]
Con el mismo reshape podemos 'verticalizar' los vectores. Por ejemplo el primero: 
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


In [12]:
#Append
V3=np.append(V1,0)
# Insert
V4=np.insert(V1,1,7)
# delete
V5=np.delete(V2,1)
print("Se puede hacer un append a los vectores, por lo que el primero quedaría:\n{}".format(V3))
print("Se puede insertar en una posición específica, por lo que podemos modificar al primero y quedaría:\n{}".format(V4))
print("Y se puede elimiar valores de un array. El segundo vector quedaría: \n{}".format(V5))


Se puede hacer un append a los vectores, por lo que el primero quedaría:
[0 1 2 3 4 5 0]
Se puede insertar en una posición específica, por lo que podemos modificar al primero y quedaría:
[0 7 1 2 3 4 5]
Y se puede elimiar valores de un array. El segundo vector quedaría: 
[ 10  25  50 100]


In [13]:
print("Se pueden apilar los vectores horizontalmente o verticalmente para generar una matriz")
print("Horizontalmente dá\n{}".format(np.hstack((V1[:5],V2))))
print("Verticalmente dá\n{}".format(np.vstack((V1[:5],V2))))

Se pueden apilar los vectores horizontalmente o verticalmente para generar una matriz
Horizontalmente dá
[  0   1   2   3   4  10  15  25  50 100]
Verticalmente dá
[[  0   1   2   3   4]
 [ 10  15  25  50 100]]


In [14]:
print("También son importantes las funciones np.c_ y np.r_")

print("np.c_ a M1 dá:\n{}".format(np.c_[M1,[0,0]]))

print("np.r_ a M1 dá:\n{}".format(np.r_[M1,[[0,0,0]]]))

También son importantes las funciones np.c_ y np.r_
np.c_ a M1 dá:
[[1 2 3 0]
 [4 5 6 0]]
np.r_ a M1 dá:
[[1 2 3]
 [4 5 6]
 [0 0 0]]


In [15]:
print("Se pueden crear arrays de 1 o 0 con no.ones y np.zeros")

print("Ejemplo:\n{}\n{}".format(np.zeros(5),np.ones(10)))

Se pueden crear arrays de 1 o 0 con no.ones y np.zeros
Ejemplo:
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


Algunas funciones extras que pueden ser útiles

In [20]:
print("------------------------------------------")
print("Extras")
print("------------------------------------------")


#Creamos una matriz cuadrada para usar de ejemplo:
M3 = np.array([[1,2,3],[2,1,3],[3,1,2]])
print("Se puede obtener la inversa de una matriz.\n La inversa de la matriz 3 dá:\n {}".format(np.linalg.inv(M3)))

print("Se puede obtener el determinante de una matriz. El determinante de la matriz 3 dá: \n{}".format(np.linalg.det(M3)))

print("Lo mismo con el rango:\n{}".format(np.linalg.matrix_rank(M3)))
w, v = np.linalg.eig(M3)
print("Y también los autovalores y autovectores:\nAutovalores :{}\nAutovectores :{}".format(w,v)) # Obs, los autovectores son columnas! El primero sería v[:,0]

print("Se puede calcular la norma de un vector. La norma del vector 1 dá:\n{}".format(np.linalg.norm(V1)))

------------------------------------------
Extras
------------------------------------------
Se puede obtener la inversa de una matriz.
 La inversa de la matriz 3 dá:
 [[-0.16666667 -0.16666667  0.5       ]
 [ 0.83333333 -1.16666667  0.5       ]
 [-0.16666667  0.83333333 -0.5       ]]
Se puede obtener el determinante de una matriz. El determinante de la matriz 3 dá: 
6.000000000000001
Lo mismo con el rango:
3
Y también los autovalores y autovectores:
Autovalores :[ 6.         -1.00000001 -0.99999999]
Autovectores :[[ 0.57735027  0.51449576 -0.51449575]
 [ 0.57735027  0.51449575 -0.51449576]
 [ 0.57735027 -0.68599434  0.68599434]]
Se puede calcular la norma de un vector. La norma del vector 1 dá:
7.416198487095663


Extra con SciPy

In [17]:
# Podemos encontrar el núcleo de una matriz con el paquete SciPy
from scipy.linalg import null_space
M4 = np.array([[1,1],[1,1]])
Zero = null_space(M4,rcond=1e-36)
print("El núcleo de M4 es:\n {}".format(Zero))

#Obs: Los resultados son aproximados, pero el error es minúsculo. Se puede mirar la documentación para más detalles en
# https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.null_space.html .



El núcleo de M4 es:
 [[-0.70710678]
 [ 0.70710678]]


Carga de csv

In [18]:
# Se pueden cargar csv con NumPy de la siguiente manera:

data = np.genfromtxt("csv/train.csv", delimiter=',',skip_header=1,dtype=int)
encabezado=np.genfromtxt("csv/train.csv", delimiter=',',max_rows=1,dtype=str)
print(encabezado)
print(data)

# Se puede guardar con np.savetxt

np.savetxt("csv\ejemplo.csv", data,delimiter=',',fmt="%.4f")



['PassengerId' 'Survived' 'Pclass' 'Name' 'Sex' 'Age' 'SibSp' 'Parch'
 'Ticket' 'Fare' 'Cabin' 'Embarked']
[[  1   0   3 ...   7  -1  -1]
 [  2   1   1 ...  71  -1  -1]
 [  3   1   3 ...   7  -1  -1]
 ...
 [889   0   3 ...  23  -1  -1]
 [890   1   1 ...  30  -1  -1]
 [891   0   3 ...   7  -1  -1]]
